### ISSUE TITLE
IG chairs to reply to ATSC liaison, offering for the IG  to review ATSC perceived gaps in Open Web  Platform

### ISSUE THREAD

**Issue by yfuna** [w3c/Web-and-TV-IG#4]

**Comment by g13e** [comment]
yosuke, how do you assign an issue? after the meeting we agreed Mark will take care of drafting a response, so we can assign it to mark (I'll then look through the others task and assign to myself anything that I will take care of)

**Comment by yfuna** [comment]
Sounds good. I'll assign this item to Mark shortly. If it comes up that he is busy later, I can help him in drafting the response.
I'd appreciate if you could take some action items.

**Comment by mavgit** [comment]
I talked with the W3C-ATSC Liaison, Mike Dolan, at another meeting we both attend. He told me that now would not be a good time for this second liaison reply, given current ATSC activities. So, I think we should consider the specific ATSC liaison with questions about the TV Control API as having been answered by the CG and close the open action item on this. The more general issues of coordinating video spec efforts can be addressed separately from this liaison.
